services:
  - type: web
    name: pixhare
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: BASE_URL
        sync: false